name = "report-writer"
language = "rust"
type = "actor"
version = "0.1.0"

[actor]
claims = ["wasmcloud:sqldb", "wasmcloud:builtin:logging", "wasmcloud:messaging"]
call-alias = "dtbh/report-writer"

[rust]
target_path = "../../target"