name = "scanner-template"
language = "rust"
type = "actor"
version = "0.1.0"

[actor]
claims = ["wasmcloud:httpclient", "wasmcloud:builtin:logging"]
call_alias = "dtbh/scanner/template"

[rust]
target_path = "../../../target"