name = "scanner-template"
language = "rust"
type = "actor"
version = "0.1.0"

[actor]
claims = ["wasmcloud:httpclient", "wasmcloud:builtin:logging"]
call-alias = "dtbh/scanner/template"

[rust]
target_path = "../../target"