name = "orchestrator"
language = "rust"
type = "actor"
version = "0.1.0"

[actor]
claims = ["jclmnop:orchestrator", "wasmcloud:builtin:logging", "wasmcloud:messaging", "jclmnop:endpoint_enumerator_callback", "jclmnop:endpoint_enumerator"]
call_alias = "dtbh/orchestrator"

[rust]
target_path = "../../target"